lostandfound/config/routes.rb
Rails.application.routes.draw do

  resources :items do
  	collection do 
  		get 'search'
  		get 'result'
  	end
  end

end

lostandfound/app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :type
end

lostandfound/app/models/type.rb
class Type < ActiveRecord::Base
        has_many :items
end

lostandfound/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lostandfound/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end
  
  def search
      
  end
  
  def result
  		andor = params.fetch(:and_or)
  		title = params.fetch(:title)
  		category = params.fetch(:category)
  		
  		if andor=="and"
  			@items = Item.where(title: title).where(category: category)
  		else
  			@items = Item.where("title LIKE ? OR category LIKE ?", title, category)
  		end
 
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :owner, :category)
    end
end

lostandfound/app/helpers/application_helper.rb
module ApplicationHelper
end

lostandfound/app/helpers/items_helper.rb
module ItemsHelper
end

lostandfound/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_area :owner %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lostandfound/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

lostandfound/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.owner %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %> |
<%= link_to 'Search', search_items_path %>

lostandfound/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

lostandfound/app/views/items/result.html.erb
<h2>Search Results</h2>


<table class = "table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.owner %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', search_items_path %>

lostandfound/app/views/items/search.html.erb
<div class="col-md-offset-1 col-md-4">
  <h1>Search</h1>
    <%= form_tag(result_items_path, method: "get", class: "form") do %>

      <div class="form-group">
        <label>Match both category AND title or EITHER</label>
        <%= select_tag(:and_or, 
              options_for_select(
              [['BOTH', "and"], 
               ['EITHER', "or"]
              ]), class: "form-control") %>
      </div>


      <div class="form-group">
        <label>Title</label>
        <%= text_field_tag(:title, "", class: "form-control") %>
      </div>
      
    <div class="form-group">
        <label>Category</label>
        <%= select_tag(:category, 
              options_for_select(
              [['Computer', "Computer"], 
               ['Phone', "Phone"], 
               ['Book', "Book"]
              ]), class: "form-control") %>
      </div>

      <%= submit_tag("Search", class: "btn btn-default") %>
    <% end %>
</div>

<%= link_to 'Back', items_path %>

lostandfound/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @item.owner %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

lostandfound/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostandfound</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>